name: formae-mcp-package

on:
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write
  contents: read
  packages: write
  attestations: write

env:
  OPS_PKG_CRT: ${{ secrets.OPS_PKG_CRT }}
  OPS_PKG_KEY: ${{ secrets.OPS_PKG_KEY }}
  OPS_TREE_CONF: ${{ secrets.OPS_TREE_CONF }}

jobs:
  pkg_linux_arm64:
    runs-on: ubuntu-24.04-arm

    concurrency:
      group: opkg_linux_arm64
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install Orbital
        run: |
          bash -c "$(curl -fsSL https://hub.platform.engineering/get/setup.sh)" -- install --yes orbital

      - name: Add PEL to PATH
        run: echo "/opt/pel/bin" >> $GITHUB_PATH

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.1'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::897722706215:role/github-pel
          role-session-name: PublishSession

      - name: Build and Publish
        run: just publish

  pkg_linux_x8664:
    runs-on: ubuntu-latest

    concurrency:
      group: opkg_linux_x8664
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install Orbital
        run: |
          bash -c "$(curl -fsSL https://hub.platform.engineering/get/setup.sh)" -- install --yes orbital

      - name: Add PEL to PATH
        run: echo "/opt/pel/bin" >> $GITHUB_PATH

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.1'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::897722706215:role/github-pel
          role-session-name: PublishSession

      - name: Build and Publish
        run: just publish

  pkg_macos_arm64:
    runs-on: macos-latest

    concurrency:
      group: opkg_macos_arm64
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install Orbital
        run: |
          bash -c "$(curl -fsSL https://hub.platform.engineering/get/setup.sh)" -- install --yes orbital

      - name: Add PEL to PATH
        run: echo "/opt/pel/bin" >> $GITHUB_PATH

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.1'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::897722706215:role/github-pel
          role-session-name: PublishSession

      - name: Build and Publish
        run: just publish

  pkg_macos_x8664:
    runs-on: macos-15-intel

    concurrency:
      group: opkg_macos_x8664
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install Orbital
        run: |
          bash -c "$(curl -fsSL https://hub.platform.engineering/get/setup.sh)" -- install --yes orbital

      - name: Add PEL to PATH
        run: echo "/opt/pel/bin" >> $GITHUB_PATH

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.1'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::897722706215:role/github-pel
          role-session-name: PublishSession

      - name: Build and Publish
        run: just publish
